p/autopkgtest: fix v3 swift auth configuration check
In swift v3, the tenant is replaced by the project, so better update the
check accordingly.
This fixes a stacktrace in production happening because the
`ADT_SWIFT_TENANT` config had been dropped for some reasons.

Stacktrace:
```
Traceback (most recent call last):
  File "/var/lib/security-britney/britney2-ubuntu/britney.py", line 1623, in <module>
    Britney().main()
  File "/var/lib/security-britney/britney2-ubuntu/britney.py", line 400, in __init__
    self._policy_engine.initialise(self, self.hints)
  File "/var/lib/security-britney/britney2-ubuntu/britney2/policies/policy.py", line 35, in initialise
    policy.initialise(britney)
  File "/var/lib/security-britney/britney2-ubuntu/britney2/policies/autopkgtest.py", line 256, in initialise
    not self.options.adt_swift_tenant or
AttributeError: 'Values' object has no attribute 'adt_swift_tenant'
```