Disable autohinting again
Britney has been crashing since the 05:53:38 run on 2026-04-04:
I: [2026-04-04T08:00:39+0000] - > Processing hints from the auto hinter
...
RecursionError: maximum recursion depth exceeded

Revert "Re-enable autohinting"

This reverts commit 2d14692555b07bc5b4d437685fec8c01220b8944.